### ISSUE TITLE
Error: PERMISSION_DENIED: Missing or insufficient permissions

### ISSUE THREAD

**Issue by ansidev** [ahsankhatri/firestore-php#3]
I tried to write to FireStore but the server responded 403 PERMISSION_DENIED: Missing or insufficient permissions.

The database rule is:
```
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth.uid != null;
    }
  }
}
```

If I change rule to `allow read, write: if true;` (turn off database security), it's OK.

**Comment by ahsankhatri** [comment]
Please update your dependency with version 2.0.0 which i've added support for Authentication, let me know your thoughts on this.

**Comment by ansidev** [comment]
I'm sorry for the late response.

Firstly, the new version doesn't resolve the problem or maybe I missed something.

After reviewing the code base, there are some problems:
- Class name problem relates to "All files prefixed changed from FireStore to Firestore": I'm not sure if you are using Windows and you renamed files using Window Explorer, the changes only affect to new added files. You can check it on github.com or git log.
- You replaced the class FireStoreApiClient with FirestoreClient, and this point isn't mentioned in the changelog and/or the examples.
- There is no test to make sure if your code works properly.

**Comment by ahsankhatri** [comment]
Actually i was developing on other location and i finished it with copying entire ‘src’ directory, i had to use ‘git mv’ for those renaming, and appology for documentation of few sections.
